### ISSUE TITLE
Can a single assertion be exchanged via QR code?

### ISSUE THREAD

**Issue by amiller-ims** [IMSGlobal/openbadges-specification#357] opened 2022-03-14 23:27 UTC
Use case https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#assertion-issuance-without-wallet-qr-code says "The participant's employer has an application that can view and verify VCs that are printed as QR codes."

The [OB 3.0 Charter](https://www.imsglobal.org/sites/default/files/OB-CLR/OpenBadgesv3p0Charter.pdf) does not mention QR codes. 

Should we add a normative section on how to do this in OB 3.0? If it is "big", the answer is no.

I don't know enough about it to provide guidance to the project group.

**Comment by kayaelle** [comment] 2022-03-23 16:46
The use of QR codes is outside of the scope of Open Badges. It's a link vehicle used by some VC implementations but also not explicitly part of the VC specification either.

**Comment by amiller-ims** [comment] 2022-03-23 17:34
@danblickensderfer Do you know who authored the use case that says, "The participant's employer has an application that can view and verify VCs that are printed as QR codes."?

We should probably get them to weigh in on the importance of that use case.

**Comment by danblickensderfer** [comment] 2022-03-23 20:11
I do not. This use case was added to the [original shared use case doc ](https://docs.google.com/document/d/1LfaqJajQK8HECizxZ2YIHkZQ_9HnD0jvyVasZegBuXY/edit#heading=h.y2j5kgri89n3) on October 7, 2021, 8:40 PM by an anonymous user. 

I can poll the work group to see if this has a sponsor/author to vouch for importance. The work group did agree that remaining use cases without sponsors or otherwise lacking enough detail to be actionable should go into the backlog of non-actionable use cases for archival purposes. 

The use case appears to reduce to (via Goal of the Primary Actor) "be able to show that they hold current certification for SFA from the Red Cross which qualifies them to be a workplace first aid attendant and gives them a raise for the extra job role;" is this covered adequately already in OB 3.0 (support for QR codes notwithstanding)? @amiller-ims

**Comment by roverwolf** [comment] 2022-03-31 18:21
I was the original author.

It may be that there is no intent that OB 3.0 should be able to replace traditional evidence of learning certificates in many cases such as this one, which can then make this use case out of scope.  This use case was just modifying an existing flow of events to use an OB instead of a traditional paper certificate.

The issue is that most of the use cases defined for providing an OB to a party such as an employer require a "wallet" of some sort, which is not feasible for a segment of the population, and this use case was added to provide an alternative.

https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#assertion-issuance-without-a-wallet mentioned QR codes in an alternative flow.

**Closed** 2022-05-12 15:36 UTC
Labels: 3p0, candidate_final
